/**
 * Artifacts as little pictures, for the hero screen: each one drawn in code, 16 pixels square,
 * lit from the top left and inked round like every sprite. An artifact with no picture of its own
 * shows its slot's.
 */
import type { ArtifactId, Slot } from '../content/artifacts';
import { ARTIFACTS } from '../content/artifacts';
import { MORE_PICTURES } from './artifactPictures';
import { Bitmap, outline } from './bitmap';
import { EARTH, GOLD, INK, LEAF, NEUTRAL, PARCHMENT, PLUM, RED, SAND, STONE, WATER, WOOD, BLUE } from './palette';

export const ICON_SIZE = 16;

const drawn = new Map<string, Bitmap>();

/** The letters the pictures are drawn in. */
const KEY: Record<string, number> = {
  o: INK,
  S: STONE[7], s: STONE[5], t: STONE[3], u: STONE[1],
  G: GOLD[6], g: GOLD[4], h: GOLD[2],
  W: WOOD[5], w: WOOD[3], v: WOOD[1],
  R: RED[5], r: RED[3], q: RED[1],
  B: BLUE[5], b: BLUE[3], n: BLUE[1],
  L: LEAF[7], l: LEAF[5], k: LEAF[3], j: LEAF[1],
  N: NEUTRAL[7], m: NEUTRAL[5], M: NEUTRAL[3],
  E: EARTH[6], e: EARTH[4], d: EARTH[2],
  P: PLUM[4], p: PLUM[2], i: PLUM[1],
  C: PARCHMENT[6], c: PARCHMENT[4], a: PARCHMENT[2],
  X: WATER[9], x: WATER[7], z: WATER[4],
  y: SAND[4], Y: SAND[5],
  Q: RED[0],
};

const PICTURES: Partial<Record<ArtifactId, string[]>> = {
  swordOfAldmoor: [
    '...............S',
    '..............St',
    '.............St.',
    '............St..',
    '...........St...',
    '..........St....',
    '.........St.....',
    '........St......',
    '....g..St.......',
    '.....GSt........',
    '......G.........',
    '.....w.g........',
    '....w...h.......',
    '...v............',
    '..B.............',
    '................',
  ],
  carvingKnife: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......SSSSSS...',
    '.WWWWgSSSSSSSSS.',
    '.wwwwgsssssssst.',
    '.vvvvgtttttttt..',
    '.......tttt.....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  abbotsStaff: [
    '..........GGG...',
    '.........G...g..',
    '.........G...g..',
    '..........g.gh..',
    '...........Wh...',
    '..........Ww....',
    '.........Ww.....',
    '........Ww......',
    '.......Ww.......',
    '......Ww........',
    '.....Ww.........',
    '....Ww..........',
    '...Ww...........',
    '..Wv............',
    '.vv.............',
    '................',
  ],
  brannocsLance: [
    '...............S',
    '..............St',
    '.............St.',
    '............ss..',
    '..........BBw...',
    '.........BBbw...',
    '........Bbb.W...',
    '........bb.W....',
    '..........W.....',
    '.........W......',
    '........Ww......',
    '.......gw.......',
    '......Wg........',
    '.....Ww.........',
    '....Ww..........',
    '...v............',
  ],
  twinWand: [
    '.G............G.',
    'GNG..........GNG',
    '.G............G.',
    '..W..........W..',
    '...W........W...',
    '....W......W....',
    '.....W....W.....',
    '......W..W......',
    '.......Ww.......',
    '......wWWw......',
    '.....w....w.....',
    '....w......w....',
    '...w........w...',
    '..v..........v..',
    '.v............v.',
    '................',
  ],
  breastplate: [
    '................',
    '..ggg......ggg..',
    '.gSSSg....gstth.',
    '.gSSSSggggsstth.',
    '..gSSSSSSssstth.',
    '..gSSSSSSsssth..',
    '...SSSSSSsssst..',
    '...SSSSSSsssst..',
    '...SSSSSSsssst..',
    '...gSSSSSssstg..',
    '....SSSSSssst...',
    '....gSSSSsstg...',
    '....gggggggggh..',
    '....sSSsstsstt..',
    '....tssstttttt..',
    '................',
  ],
  trollhide: [
    '................',
    '..EEe......eed..',
    '.EEEEe....eeedd.',
    '.EEEEEeeeeeeedd.',
    '..EEEEEEeeeedd..',
    '..EEEEEEeeeedd..',
    '...EEEEEeeeed...',
    '...EEoEEeeoed...',
    '...EEEEEeeeed...',
    '...EEoEEeeoed...',
    '...EEEEEeeeed...',
    '...EEoEEeeoed...',
    '...EEEEEeeeed...',
    '...dddddddddd...',
    '................',
    '................',
  ],
  harrowgateMail: [
    '................',
    '...SsS....sts...',
    '..SsSsSsSstststs',
    '.SsSsSsSststststt',
    '.sSsSsSstststst.',
    '..SsSsSsstststt.',
    '..sSsSsststst...',
    '..SsSsSstststt..',
    '..sSsSsststst...',
    '..SsSsSstststt..',
    '..sSsSsststst...',
    '..SsSsSstststt..',
    '..gggggggggghh..',
    '..sSsSsststst...',
    '..tstststststt..',
    '................',
  ],
  greenwoodCloak: [
    '......llk.......',
    '.....lLLlk......',
    '....lLjjjlk.....',
    '....lj.C.jk.....',
    '....lj...jk.....',
    '...lLlg.glkk....',
    '...lLLlllkkk....',
    '..lLLLllllkkk...',
    '..lLLlllllkkk...',
    '..lLLlllllkkkj..',
    '.lLLllllllkkkj..',
    '.lLLlllllllkkj..',
    '.lLlllllllkkkj..',
    '.lllklklklkjkj..',
    '..jj.jj.jj.jj...',
    '................',
  ],
  dwarvenHelm: [
    '................',
    '................',
    '......SSss......',
    '....SSSSssst....',
    '...SSSSsssstt...',
    '...SSSSsssttt...',
    '..SSSSssssttth..',
    '..gggggggggghh..',
    '..SSt.sSt..stt..',
    '..SSt.sSt..stt..',
    '..SSt.sSt..stt..',
    '..SSt..s...stt..',
    '...t...s....t...',
    '................',
    '................',
    '................',
  ],
  helmOfFarSight: [
    '..........RR....',
    '.........RRr....',
    '......SSsRr.....',
    '....SSSSssst....',
    '...SSSSsssstt...',
    '...SSNNNNNstt...',
    '..SSNNBBnNNtth..',
    '..SSNNBnnNNtth..',
    '..SSSNNNNNsttt..',
    '..gggggggggghh..',
    '..SSt......stt..',
    '..SSt......stt..',
    '...t........t...',
    '................',
    '................',
    '................',
  ],
  crystalBall: [
    '................',
    '.....XXXxx......',
    '....XNXxxxz.....',
    '...XNXxxxxzz....',
    '...XXxxxxxzz....',
    '...xxxxxxxzz....',
    '...xxxxxxzzz....',
    '....xxxxzzz.....',
    '.....zzzzz......',
    '.....GgggG......',
    '....GGggghh.....',
    '...GGgggghhh....',
    '...hhhhhhhhh....',
    '................',
    '................',
    '................',
  ],
  oldBanner: [
    '..G.............',
    '..WRRRRRRRRR....',
    '..WRRRRRRRRRr...',
    '..WRRRNNRRRRr...',
    '..WRRRNNRRRrr...',
    '..WRRNNNNRRrr...',
    '..WRRNoNNRRrr...',
    '..WRRNNNNRrrr...',
    '..WRRRR.RRrr....',
    '..WRRR...Rrr....',
    '..WRR.....rr....',
    '..W.............',
    '..W.............',
    '..w.............',
    '..w.............',
    '..v.............',
  ],
  fenBanner: [
    '..G.............',
    '..WBBBBBBBBBB...',
    '..WBBBBNNBBBb...',
    '..WBBBBNBBBBb...',
    '..WBBBBNNBBbb...',
    '..WBBBNNNNBbb...',
    '..WBBBNNNNNbb...',
    '..WBBBBNNBbbb...',
    '..WBBBBNBNbbb...',
    '..WBBBbbbbbbb...',
    '..WBBbb..bbbb...',
    '..WBb.....bb....',
    '..W.............',
    '..w.............',
    '..w.............',
    '..v.............',
  ],
  luckyHorseshoe: [
    '................',
    '................',
    '..SSs......sst..',
    '..SSs......stt..',
    '..SoS......sot..',
    '..SSs......stt..',
    '..SSs......stt..',
    '..SoS......sot..',
    '..SSSs....sstt..',
    '...SSSssssstt...',
    '....SSsssstt....',
    '......tttt......',
    '................',
    '................',
    '................',
    '................',
  ],
  wizardsButton: [
    '................',
    '................',
    '................',
    '.....PPPPPp.....',
    '....PPPPPPpp....',
    '...PPPPPPPPpp...',
    '...PPoPPPoPpp...',
    '...PPPPGPPPpp...',
    '...PPoPPPoPpp...',
    '...PPPPPPPPpp...',
    '....PPPPPPpp....',
    '.....ppppppi....',
    '................',
    '................',
    '................',
    '................',
  ],
  goldenFeather: [
    '..............G.',
    '............GGg.',
    '..........GGGgh.',
    '.........GGGggh.',
    '........GGGggh..',
    '.......GGGggh...',
    '......GGGggh....',
    '.....GGGggh.....',
    '....GGGggh......',
    '....GGggh.......',
    '...GGgh.........',
    '...Ggh..........',
    '..gh............',
    '.g..............',
    'g...............',
    '................',
  ],
  millersLoaf: [
    '................',
    '................',
    '................',
    '.....YYYYYy.....',
    '...YYYYYYYYyy...',
    '..YYyYYyYYyYyy..',
    '..YYYyYYyYYyyy..',
    '.YYYYYyYYyYyyyy.',
    '.YYYYYYYYYyyyyy.',
    '.yYYYYYYYyyyyye.',
    '..yyyyyyyyyyee..',
    '...eeeeeeeeee...',
    '................',
    '................',
    '................',
    '................',
  ],
  eelskinBoots: [
    '................',
    '...lll...lll....',
    '...lLk...lLk....',
    '...lLk...lLk....',
    '...lLk...lLk....',
    '...lLk...lLk....',
    '...lLk...lLk....',
    '...lLkk..lLkk...',
    '...lLLkk.lLLkk..',
    '...lLLLkklLLLkk.',
    '...jjjjjjjjjjjj.',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  goblinCharm: [
    '..d..........d..',
    '...d........d...',
    '....d......d....',
    '.....d....d.....',
    '......dddd......',
    '......CccC......',
    '.....lLLLlk.....',
    '....lLNLLllk....',
    '...lLNLLLlllk...',
    '...lLLLLllllk...',
    '...llLLllllkk...',
    '....llllllkk....',
    '.....kkkkkk.....',
    '......kkkk......',
    '................',
    '................',
  ],
  astrolabe: [
    '.......G........',
    '......GgG.......',
    '.....GGGGGgg....',
    '....GGgggggghh..',
    '...GGg.....ghh..',
    '...Gg..W....gh..',
    '...Gg...W...gh..',
    '...Gg..NW...gh..',
    '...Gg.......gh..',
    '...Ggg.....ghh..',
    '....ggggggghh...',
    '.....hhhhhhh....',
    '................',
    '................',
    '................',
    '................',
  ],
  poachersHorn: [
    '................',
    '...........gG...',
    '..........CCg...',
    '........CCCc....',
    '......CCCCc.....',
    '.....CCCCc......',
    '....gCCCc.......',
    '....gCCCc.......',
    '.....CCCCc......',
    '......CCCCCca...',
    '.......CCCCCCea.',
    '........gCCCCed.',
    '.........CCCCed.',
    '..........aaeda.',
    '................',
    '................',
  ],
  silverSignet: [
    '................',
    '................',
    '....SSSSSSSs....',
    '...SMMMMMMMst...',
    '...SMmGGGmMst...',
    '...SMMGRGMMst...',
    '....SsssssstM...',
    '....Ss....ts....',
    '...Ss......ts...',
    '..Ss........t...',
    '..Ss........t...',
    '..Ss........t...',
    '...Ss......ts...',
    '....Ss....ts....',
    '.....sssstt.....',
    '................',
  ],
};

/** The hero's four stats, as HoMM2 shows them: a sword, a shield, a wand's spark and a book. */
const STAT_PICTURES: Record<'attack' | 'defence' | 'spellPower' | 'knowledge', string[]> = {
  attack: [
    'S..............S',
    'tS............St',
    '.tS..........St.',
    '..tS........St..',
    '...tS......St...',
    '....tS....St....',
    '.....tS..St.....',
    '......tSSt......',
    '......gStg......',
    '.....g.tt.g.....',
    '....G.g..g.G....',
    '...w.G....G.w...',
    '..w..........w..',
    '.v............v.',
    'G..............G',
    '................',
  ],
  defence: [
    '................',
    '..rRRRRRRRRRRq..',
    '..RRRRRGgRRRrq..',
    '..RRRRRGgRRrrq..',
    '..RRRRRGgRrrrq..',
    '..RGGGGGgggggq..',
    '..RgggggghhhhQ..',
    '..RRRRRGgrrrrq..',
    '...RRRRGgrrrq...',
    '...RRRRGgrrrq...',
    '....RRRGgrrq....',
    '.....RRGgrq.....',
    '......RGgq......',
    '.......qq.......',
    '................',
    '................',
  ],
  spellPower: [
    '.......G........',
    '.......G........',
    '......GNG.......',
    'G..GGGNNNGGG..G.',
    '.G..GNNNNNG..G..',
    '.....GNNNG......',
    '.....GG.GG......',
    '....G.....G.....',
    '...........W....',
    '............W...',
    '.............W..',
    '..............w.',
    '...............v',
    '................',
    '................',
    '................',
  ],
  knowledge: [
    '................',
    '................',
    '..BBBBB..BBBBB..',
    '.BCCCCCBBCCCCCb.',
    '.BCaaaCBBCaaaCb.',
    '.BCCCCCBBCCCCCb.',
    '.BCaaaCBBCaaaCb.',
    '.BCCCCCBBCCCCCb.',
    '.BCaaaCBBCaaaCb.',
    '.BCCCCCBBCCCCCb.',
    '.BCCCCCBBCCCCCb.',
    '.bbbbbbbbbbbbbb.',
    '.......nn.......',
    '................',
    '................',
    '................',
  ],
};

/** A stat's picture, inked round. */
export function statIcon(id: keyof typeof STAT_PICTURES): Bitmap {
  const key = `stat:${id}`;
  let icon = drawn.get(key);
  if (!icon) {
    icon = outline(paint(STAT_PICTURES[id]), INK);
    drawn.set(key, icon);
  }
  return icon;
}

/** Each slot's picture, for artifacts without their own and for the empty slot's faint outline. */
const SLOT_PICTURE: Record<Slot, ArtifactId> = { weapon: 'swordOfAldmoor', armour: 'breastplate', helm: 'dwarvenHelm', banner: 'oldBanner', trinket: 'luckyHorseshoe', trinket2: 'luckyHorseshoe', trinket3: 'luckyHorseshoe' };

function paint(rows: string[]): Bitmap {
  const b = new Bitmap(ICON_SIZE, ICON_SIZE);
  rows.forEach((row, y) => [...row].slice(0, ICON_SIZE).forEach((ch, x) => KEY[ch] !== undefined && b.set(x, y, KEY[ch])));
  return b;
}

/** Any 16-pixel picture drawn in these letters, inked round, as the icons are: the battle's pointers use it too. */
export const picture = (rows: string[]): Bitmap => outline(paint(rows), INK);

/** An artifact's picture, inked round. */
export function artifactIcon(id: ArtifactId): Bitmap {
  let icon = drawn.get(id);
  if (!icon) {
    icon = outline(paint(PICTURES[id] ?? MORE_PICTURES[id] ?? PICTURES[SLOT_PICTURE[ARTIFACTS[id].slot]]!), INK);
    drawn.set(id, icon);
  }
  return icon;
}

/** An empty slot's faint outline, pressed into the parchment. */
export function slotGhost(slot: Slot): Bitmap {
  const key = `slot:${slot}`;
  let ghost = drawn.get(key);
  if (!ghost) {
    const shape = paint(PICTURES[SLOT_PICTURE[slot]]!);
    ghost = new Bitmap(ICON_SIZE, ICON_SIZE);
    for (let i = 0; i < shape.data.length; i++) if (shape.data[i]) ghost.data[i] = PARCHMENT[2];
    drawn.set(key, ghost);
  }
  return ghost;
}
